"""Fix all 8

Revision ID: 007817816f7e
Revises: e5cfc4ef2791
Create Date: 2026-07-16 09:04:30.577780
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '007817816f7e'
down_revision: Union[str, None] = 'e5cfc4ef2791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_programs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('commission_type', sa.String(length=20), nullable=False),
    sa.Column('commission_value', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cookie_duration_days', sa.Integer(), nullable=True),
    sa.Column('minimum_payout', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affiliates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('program_id', sa.UUID(), nullable=False),
    sa.Column('affiliate_code', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_earnings', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pending_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('paid_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_referrals', sa.Integer(), nullable=True),
    sa.Column('total_conversions', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['affiliate_programs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliates_affiliate_code'), 'affiliates', ['affiliate_code'], unique=True)
    op.create_table('email_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=500), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('from_email', sa.String(length=255), nullable=False),
    sa.Column('from_name', sa.String(length=255), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('target_user_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_opened', sa.Integer(), nullable=True),
    sa.Column('total_clicked', sa.Integer(), nullable=True),
    sa.Column('total_bounced', sa.Integer(), nullable=True),
    sa.Column('total_unsubscribed', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('target_user_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_delivered', sa.Integer(), nullable=True),
    sa.Column('total_opened', sa.Integer(), nullable=True),
    sa.Column('total_clicked', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sms_campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('target_user_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_recipients', sa.Integer(), nullable=True),
    sa.Column('total_sent', sa.Integer(), nullable=True),
    sa.Column('total_delivered', sa.Integer(), nullable=True),
    sa.Column('total_failed', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affiliate_earnings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affiliate_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('custom_slug', sa.String(length=100), nullable=True),
    sa.Column('total_clicks', sa.Integer(), nullable=True),
    sa.Column('total_conversions', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_links_code'), 'affiliate_links', ['code'], unique=True)
    op.create_table('campaign_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('sms_campaign_id', sa.UUID(), nullable=True),
    sa.Column('push_campaign_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('extra_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['email_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['push_campaign_id'], ['push_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sms_campaign_id'], ['sms_campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('affiliate_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('link_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('converted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['link_id'], ['affiliate_links.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliate_clicks')
    op.drop_table('campaign_logs')
    op.drop_index(op.f('ix_affiliate_links_code'), table_name='affiliate_links')
    op.drop_table('affiliate_links')
    op.drop_table('affiliate_earnings')
    op.drop_table('sms_campaigns')
    op.drop_table('push_campaigns')
    op.drop_table('email_campaigns')
    op.drop_index(op.f('ix_affiliates_affiliate_code'), table_name='affiliates')
    op.drop_table('affiliates')
    op.drop_table('affiliate_programs')
    # ### end Alembic commands ###
