"""Fix all 15

Revision ID: 0b9bede90b71
Revises: cdca1a38a2a1
Create Date: 2026-07-17 11:55:14.295630
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '0b9bede90b71'
down_revision: Union[str, None] = 'cdca1a38a2a1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
