"""describe the change

Revision ID: 1c1235063c9f
Revises: e5f6a7b8c9d0
Create Date: 2026-07-15 11:27:45.606485
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '1c1235063c9f'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('coupons_code_key'), 'coupons', type_='unique')
    op.drop_index(op.f('ix_loyalty_point_transactions_user_id'), table_name='loyalty_point_transactions')
    op.drop_index(op.f('ix_referral_rewards_referrer_id'), table_name='referral_rewards')
    op.drop_index(op.f('ix_review_helpful_review_id'), table_name='review_helpful')
    op.drop_index(op.f('ix_review_helpful_user_id'), table_name='review_helpful')
    op.drop_constraint(op.f('uq_review_helpful_user_review'), 'review_helpful', type_='unique')
    op.drop_index(op.f('ix_review_reports_review_id'), table_name='review_reports')
    op.drop_index(op.f('ix_review_reports_user_id'), table_name='review_reports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_review_reports_user_id'), 'review_reports', ['user_id'], unique=False)
    op.create_index(op.f('ix_review_reports_review_id'), 'review_reports', ['review_id'], unique=False)
    op.create_unique_constraint(op.f('uq_review_helpful_user_review'), 'review_helpful', ['review_id', 'user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_review_helpful_user_id'), 'review_helpful', ['user_id'], unique=False)
    op.create_index(op.f('ix_review_helpful_review_id'), 'review_helpful', ['review_id'], unique=False)
    op.create_index(op.f('ix_referral_rewards_referrer_id'), 'referral_rewards', ['referrer_id'], unique=False)
    op.create_index(op.f('ix_loyalty_point_transactions_user_id'), 'loyalty_point_transactions', ['user_id'], unique=False)
    op.create_unique_constraint(op.f('coupons_code_key'), 'coupons', ['code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
