"""Fix all

Revision ID: 31bd36451160
Revises: b2c3d4e5f6a8
Create Date: 2026-07-15 17:02:42.815682
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '31bd36451160'
down_revision: Union[str, None] = 'b2c3d4e5f6a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
