"""add wishlist table

Revision ID: 572d8d0bf3e4
Revises: f6a7b8c9d0e1
Create Date: 2026-07-15 12:40:54.603376
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '572d8d0bf3e4'
down_revision: Union[str, None] = 'f6a7b8c9d0e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_logs_channel'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_created_at'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_status'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_user_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_templates_notification_type'), table_name='notification_templates')
    op.drop_index(op.f('ix_notification_templates_slug'), table_name='notification_templates')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_notification_templates_slug'), 'notification_templates', ['slug'], unique=True)
    op.create_index(op.f('ix_notification_templates_notification_type'), 'notification_templates', ['notification_type'], unique=False)
    op.create_index(op.f('ix_notification_logs_user_id'), 'notification_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_status'), 'notification_logs', ['status'], unique=False)
    op.create_index(op.f('ix_notification_logs_created_at'), 'notification_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_notification_logs_channel'), 'notification_logs', ['channel'], unique=False)
    # ### end Alembic commands ###
