"""Initial schema

Revision ID: 5f5527e29051
Revises: c3d4e5f6a7b8
Create Date: 2026-07-15 09:09:58.236132
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '5f5527e29051'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
