"""Fix all 9

Revision ID: 7463bdf9edf0
Revises: 007817816f7e
Create Date: 2026-07-16 09:35:01.416715
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '7463bdf9edf0'
down_revision: Union[str, None] = '007817816f7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
