"""Fix all 10

Revision ID: 9280ebd475bf
Revises: 7463bdf9edf0
Create Date: 2026-07-16 10:21:54.140054
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '9280ebd475bf'
down_revision: Union[str, None] = '7463bdf9edf0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
