"""Fix all 12

Revision ID: 929ab98087da
Revises: f10010f869e8
Create Date: 2026-07-17 09:58:05.145149
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '929ab98087da'
down_revision: Union[str, None] = 'f10010f869e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
