"""Fix all 4

Revision ID: a442ae35c832
Revises: 31bd36451160
Create Date: 2026-07-15 23:53:53.776212
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a442ae35c832'
down_revision: Union[str, None] = '31bd36451160'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'recently_viewed_products', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'wishlist_items', 'products', ['product_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'wishlist_items', type_='foreignkey')
    op.drop_constraint(None, 'recently_viewed_products', type_='foreignkey')
    # ### end Alembic commands ###
