"""Fix all 14

Revision ID: cdca1a38a2a1
Revises: 039936f2cd7f
Create Date: 2026-07-17 11:14:05.714183
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'cdca1a38a2a1'
down_revision: Union[str, None] = '039936f2cd7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
