"""Fix all 5

Revision ID: ed3135457215
Revises: a442ae35c832
Create Date: 2026-07-16 01:42:49.206553
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'ed3135457215'
down_revision: Union[str, None] = 'a442ae35c832'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gift_cards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('initial_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('remaining_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('purchaser_user_id', sa.UUID(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['purchaser_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_gift_card_code')
    )
    op.create_index(op.f('ix_gift_cards_code'), 'gift_cards', ['code'], unique=False)
    op.create_unique_constraint('uq_review_helpful_review_user', 'review_helpful', ['review_id', 'user_id'])
    op.create_unique_constraint('uq_review_report_review_user', 'review_reports', ['review_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_review_report_review_user', 'review_reports', type_='unique')
    op.drop_constraint('uq_review_helpful_review_user', 'review_helpful', type_='unique')
    op.drop_index(op.f('ix_gift_cards_code'), table_name='gift_cards')
    op.drop_table('gift_cards')
    # ### end Alembic commands ###
