"""Fix all 11

Revision ID: f10010f869e8
Revises: 9280ebd475bf
Create Date: 2026-07-16 16:24:01.706983
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f10010f869e8'
down_revision: Union[str, None] = '9280ebd475bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
