"""Fix all 6

Revision ID: f7aa4a8caa7f
Revises: ed3135457215
Create Date: 2026-07-16 06:07:30.805602
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'f7aa4a8caa7f'
down_revision: Union[str, None] = 'ed3135457215'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
